---
##################
# Basic Settings #
##################

# Web configuration
port: 80

# Image resolution Set to empty object (`{ }`) to use default resolution.
# Resolutions: 
#   Ratio: 16:9
#     1920x1080
#     2560x1440
#     640x360
resolution: { }
  # width: 2560
  # height: 1440

# The number of images to capture. Max: 99999
total_images: 10

# The interval between captures (in seconds).
interval: 2

# Enable taking pictures only within specific hours
enableTimeframe: False
waitingPeriod: 600 # seconds

# Format must be 24 hrs
startHour: 6
startMinute: 30
endHour: 20
endMinute: 30

#####################
# Advanced settings #
#####################

# ISO value. 0 = auto, 60-800 for manual ISO.
iso: 0

# Shutter speed. 0 = auto, else value in microseconds (seconds * 1000000).
shutter_speed: 0

# White balance. Set to empty object (`{ }`) to use auto white balance.
white_balance: { }
  # red_gain: 1.3
  # blue_gain: 1.75

# Rotate the images taken by the camera. Possible value are 0, 90, 180 or 270
rotation: 0

#####################
# Media control #
#####################

# Whether to create an animated gif after capturing the time-lapse images.
create_gif: False

# Whether to create an video after capturing the time-lapse images.
create_video: False